### PR TITLE
Show just the branch name (remove previous commit) when displaying git branches in quick panel

### PR DESCRIPTION
**Pull request by glenrobertson**
I found that the branches don't display very well in the quick panel with the previous commit sha and description. I removed the -v from the `git branch -v` call, so it just shows the branch name.

Thanks!

### CODE REVIEW

**Comment by titoBouzout** [comment]
What do you mean with "don't display very well", can you please take an screenshot?
Thanks

**Comment by glenrobertson** [comment]
Ah fair enough I didn't explain that very well. So currently it looks like this: http://cl.ly/421R1c0H3K1g3l1M1E3K

My idea was just to remove the previous commit sha/description so it just looks like this: http://cl.ly/1Z2q423R0C1y3t1b2A44

Hope that makes more sense.. thanks

**Comment by titoBouzout** [comment]
Thank you, Please take a look now and let me know if the text is readable again.

**Comment by titoBouzout** [comment]
I found the commit message and sha informative. This is why I want to keep it.

**Comment by titoBouzout** [comment]
Thank you

**Pull request closed without merging**
